---
version: '3.6'
services:
  validator1:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/tmp/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator1/keys:/opt/besu/keys
      - ./config/besu/p2p-ssl/validator1:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
  validator2:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator2/keys:/opt/besu/keys
      - ./config/besu/p2p-ssl/validator2:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - validator1
  validator3:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator3/keys:/opt/besu/keys
      - ./config/besu/p2p-ssl/validator3:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - validator1
  validator4:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/validator4/keys:/opt/besu/keys
      - ./config/besu/p2p-ssl/validator4:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - validator1
  rpcnode:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/rpcnode/keys:/opt/besu/keys
      - ./config/besu/p2p-ssl/rpcnode:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 8547:8547/tcp
  member1besu:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --privacy-enabled \
        --privacy-url=http://member1orion:8888 \
        --privacy-public-key-file=/config/orion/orion.pub \
        --privacy-onchain-groups-enabled=false \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/member1/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion1/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/p2p-ssl/member1besu:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - member1orion
      - validator1
  member1orion:
    image: consensys/quorum-orion:${QUORUM_ORION_VERSION:-latest}
    command: ["/config/orion.conf"]
    environment:    
      - ORION_OTHERNODES=http://member2orion:8080/,http://member3orion:8080/
      - ORION_NODEURL=http://member1orion:8080
      - ORION_CLIENTURL=http://member1orion:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion1:/keys/
      - ./logs/orion:/tmp/orion
      - ./config/orion/log-config.xml:/config/log-config.xml
  member2besu:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --privacy-enabled \
        --privacy-url=http://member2orion:8888 \
        --privacy-public-key-file=/config/orion/orion.pub \
        --privacy-onchain-groups-enabled=false \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/member2/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion2/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/p2p-ssl/member2besu:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - member2orion
      - validator1
  member2orion:
    image: consensys/quorum-orion:${QUORUM_ORION_VERSION:-latest}
    command: ["/config/orion.conf"]
    environment:    
      - ORION_OTHERNODES=http://member1orion:8080/,http://member3orion:8080/
      - ORION_NODEURL=http://member2orion:8080
      - ORION_CLIENTURL=http://member2orion:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion2:/keys/
      - ./logs/orion:/tmp/orion
      - ./config/orion/log-config.xml:/config/log-config.xml
  member3besu:
    restart: "on-failure"
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --genesis-file=/config/genesis.json \
        --node-private-key-file=/opt/besu/keys/key \
        --privacy-enabled \
        --privacy-url=http://member3orion:8888 \
        --privacy-public-key-file=/config/orion/orion.pub \
        --privacy-onchain-groups-enabled=false \
        --p2p-ssl-enabled \
        --p2p-ssl-keystore-type=JKS \
        --p2p-ssl-keystore-file=/opt/besu/p2p-ssl/keystore.jks \
        --p2p-ssl-keystore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --p2p-ssl-truststore-type=JKS \
        --p2p-ssl-truststore-file=/opt/besu/p2p-ssl/truststore.jks \
        --p2p-ssl-truststore-password-file=/opt/besu/p2p-ssl/nsspin.txt \
        --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,IBFT ;
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/config.toml:/config/config.toml
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/tmp/besu
      - ./config/besu/ibft2Genesis.json:/config/genesis.json
      - ./config/besu/networkFiles/member3/keys:/opt/besu/keys
      - ./config/orion/networkFiles/orion3/nodeKey.pub:/config/orion/orion.pub
      - ./config/besu/p2p-ssl/member3besu:/opt/besu/p2p-ssl
      - ./config/besu/static-nodes.json:/config/static-nodes.json
    depends_on:
      - member3orion
      - validator1
  member3orion:
    image: consensys/quorum-orion:${QUORUM_ORION_VERSION:-latest}
    command: ["/config/orion.conf"]
    environment:    
      - ORION_OTHERNODES=http://member1orion:8080/,http://member2orion:8080/
      - ORION_NODEURL=http://member3orion:8080
      - ORION_CLIENTURL=http://member3orion:8888
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    volumes:
      - ./config/orion/orion.conf:/config/orion.conf
      - ./config/orion/networkFiles/orion3:/keys/
      - ./logs/orion:/tmp/orion
      - ./config/orion/log-config.xml:/config/log-config.xml
  explorer:
    build: block-explorer-light/.
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
volumes:
  public-keys:
  prometheus:
  grafana:
  cakeshop:
